import type { RuntimeContractFixture, TaskDefinition } from "../runtime/contracts";

const parentTask: TaskDefinition = {
  id: "task-translate-window",
  runId: "fixture-runtime-001",
  dedupeKey: "translate:clip-raw:0-40",
  objective: "Translate the assigned dialogue and report evidence to the orchestrator.",
  parentTaskId: null,
  parentAgentId: null,
  ownerAgentId: "translate-01",
  depth: 0,
  mediaScope: [{ artifactId: "artifact-raw", trackId: "audio-1", range: [0, 40] }],
  inputArtifacts: ["artifact-raw"],
  requiredOutputs: [{ name: "caption draft", artifactKind: "caption-draft", required: true }],
  requiredCapabilities: ["media.read", "artifact.write", "task.spawn.request", "report.submit"],
  dependencies: [],
  budget: { wallMs: 60_000, toolCalls: 10, tokens: 12_000 },
  status: "working",
};

const childTask: TaskDefinition = {
  id: "task-acoustic-check",
  runId: "fixture-runtime-001",
  dedupeKey: "acoustic-check:artifact-raw:12-18",
  objective: "Compare raw audio with a derived diagnostic view and report whether evidence changed.",
  parentTaskId: parentTask.id,
  parentAgentId: "translate-01",
  ownerAgentId: null,
  depth: 1,
  mediaScope: [{ artifactId: "artifact-raw", trackId: "audio-1", range: [12, 18] }],
  inputArtifacts: ["artifact-raw"],
  requiredOutputs: [{ name: "acoustic comparison", artifactKind: "acoustic-comparison", required: true }],
  requiredCapabilities: ["media.read", "media.loop", "artifact.write", "report.submit", "memory.propose"],
  dependencies: [],
  budget: { wallMs: 30_000, toolCalls: 8, tokens: 6_000 },
  status: "defined",
};

const grants = [
  {
    capability: "media.read" as const,
    mediaScope: [{ artifactId: "artifact-raw", trackId: "audio-1", range: [12, 18] as [number, number] }],
  },
  {
    capability: "media.loop" as const,
    mediaScope: [{ artifactId: "artifact-raw", trackId: "audio-1", range: [12, 18] as [number, number] }],
  },
  { capability: "artifact.write" as const, mediaScope: [] },
  { capability: "report.submit" as const, mediaScope: [] },
  { capability: "memory.propose" as const, mediaScope: [] },
];

export const RUNTIME_CONTRACT_FIXTURES: readonly RuntimeContractFixture[] = [
  {
    id: "bounded-child-report",
    fixtureOnly: true,
    note: "Exact policy fixture only; this is not runtime evidence and no agent performed it.",
    limits: {
      maxDepth: 2,
      maxActiveWorkers: 3,
      runBudget: { wallMs: 120_000, toolCalls: 30, tokens: 30_000 },
    },
    seedTasks: [parentTask],
    seedArtifacts: [
      {
        id: "artifact-raw",
        kind: "source-audio",
        mediaClass: "raw",
        producerTaskId: parentTask.id,
        producerAgentId: "translate-01",
        sourceArtifactIds: [],
        receiptId: "receipt-ingest-001",
      },
    ],
    events: [
      {
        seq: 1,
        fixtureOnly: true,
        type: "spawn_requested",
        requestId: "spawn-001",
        requestedByTaskId: parentTask.id,
        requestedByAgentId: "translate-01",
        task: childTask,
      },
      {
        seq: 2,
        fixtureOnly: true,
        type: "spawn_decided",
        requestId: "spawn-001",
        schedulerId: "scheduler-01",
        accepted: true,
        rejection: null,
        grants,
      },
      {
        seq: 3,
        fixtureOnly: true,
        type: "agent_registered",
        agentId: "acoustic-02",
        taskId: childTask.id,
        parentTaskId: parentTask.id,
        parentAgentId: "translate-01",
        grants,
      },
      {
        seq: 4,
        fixtureOnly: true,
        type: "task_transition",
        taskId: childTask.id,
        agentId: "acoustic-02",
        status: "working",
        reason: null,
      },
      {
        seq: 5,
        fixtureOnly: true,
        type: "artifact_recorded",
        artifact: {
          id: "artifact-acoustic-comparison",
          kind: "acoustic-comparison",
          mediaClass: "derived",
          producerTaskId: childTask.id,
          producerAgentId: "acoustic-02",
          sourceArtifactIds: ["artifact-raw"],
          receiptId: "receipt-media-operation-001",
        },
      },
      {
        seq: 6,
        fixtureOnly: true,
        type: "report_submitted",
        reportId: "report-001",
        taskId: childTask.id,
        agentId: "acoustic-02",
        parentTaskId: parentTask.id,
        parentAgentId: "translate-01",
        outputArtifactIds: ["artifact-acoustic-comparison"],
        summary: "Contract fixture report with raw-to-derived lineage retained.",
      },
      {
        seq: 7,
        fixtureOnly: true,
        type: "task_transition",
        taskId: childTask.id,
        agentId: "acoustic-02",
        status: "reported",
        reason: null,
      },
      {
        seq: 8,
        fixtureOnly: true,
        type: "report_decided",
        reportId: "report-001",
        decidedByTaskId: parentTask.id,
        decidedByAgentId: "translate-01",
        accepted: true,
        reason: "Required output and receipt are present in the fixture.",
      },
      {
        seq: 9,
        fixtureOnly: true,
        type: "memory_proposed",
        proposalId: "memory-001",
        taskId: childTask.id,
        agentId: "acoustic-02",
        kind: "rule",
        evidenceArtifactIds: ["artifact-acoustic-comparison"],
      },
      {
        seq: 10,
        fixtureOnly: true,
        type: "memory_decided",
        proposalId: "memory-001",
        decidedBy: "memory-gate-01",
        accepted: false,
        reason: "A contract fixture cannot promote persistent memory.",
      },
      {
        seq: 11,
        fixtureOnly: true,
        type: "control_requested",
        requestId: "control-001",
        action: "pause",
        requestedBy: "fixture-user",
      },
      {
        seq: 12,
        fixtureOnly: true,
        type: "control_acknowledged",
        requestId: "control-001",
        runtimeId: "fixture-runtime",
        accepted: true,
        reason: "The contract requires an acknowledgement before pause can be projected.",
      },
      {
        seq: 13,
        fixtureOnly: true,
        type: "task_transition",
        taskId: childTask.id,
        agentId: "acoustic-02",
        status: "completed",
        reason: null,
      },
    ],
  },
  {
    id: "duplicate-owner-rejection",
    fixtureOnly: true,
    note: "Exact rejection fixture only; this is not runtime evidence and no scheduler performed it.",
    limits: {
      maxDepth: 2,
      maxActiveWorkers: 4,
      runBudget: { wallMs: 140_000, toolCalls: 35, tokens: 32_000 },
    },
    seedTasks: [
      parentTask,
      {
        ...childTask,
        id: "task-acoustic-existing",
        ownerAgentId: "acoustic-existing",
        status: "working",
      },
    ],
    seedArtifacts: [
      {
        id: "artifact-raw",
        kind: "source-audio",
        mediaClass: "raw",
        producerTaskId: parentTask.id,
        producerAgentId: "translate-01",
        sourceArtifactIds: [],
        receiptId: "receipt-ingest-001",
      },
    ],
    events: [
      {
        seq: 1,
        fixtureOnly: true,
        type: "spawn_requested",
        requestId: "spawn-duplicate",
        requestedByTaskId: parentTask.id,
        requestedByAgentId: "translate-01",
        task: { ...childTask, id: "task-acoustic-duplicate", budget: { wallMs: 20_000, toolCalls: 5, tokens: 4_000 } },
      },
      {
        seq: 2,
        fixtureOnly: true,
        type: "spawn_decided",
        requestId: "spawn-duplicate",
        schedulerId: "scheduler-01",
        accepted: false,
        rejection: "duplicate_owner",
        grants: [],
      },
    ],
  },
] as const;
